apiVersion: v1
kind: ConfigMap
metadata:
  name: local-configmap
  namespace: esysvendas-local
data:
  ConnectionStrings__VendasDB: "Data Source=10.102.136.174,1433;Initial Catalog=EsysVendas;User ID=sa;Password=Admin1234@;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;"
  ConnectionStrings__VendasMongoDb: testemongo
  SA_PASSWORD: "Admin1234@"
  ACCEPT_EULA: "Y"
