kind: Service
apiVersion: v1
metadata:
  namespace: esys-local
  name:  esysrabbitmanagement-nodeport
spec:
  selector:
    app:  esysrabbit
  type:  NodePort
  ports:
  - port:  15672
    nodePort: 30010
    